apiVersion: apps/v1
kind: Deployment # k8s resource kind we are creating
metadata:
  name: docker-k8s-assignment
spec:
  selector:
    matchLabels:
      app: docker-k8s-assignment
  replicas: 2 # number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: docker-k8s-assignment
    spec:
      containers:
        - name: docker-k8s-assignment
          image: githubofsourav/docker-k8s-assignment:1.0 # image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent # k8s first checks in local, if not present than checks in docker-hub
          ports:
            - containerPort: 8081 # port that the container is running on in the cluster